<script lang="ts" setup>
</script>

<template>
  <button
      class="
      border-s
      border-e
      border-primary
      active:shadow-inner
      text-primary
      focus:outline-none
      cursor-default
      px-4
      py-1
      rounded
      shadow-xl
      flex
      justify-center
      items-center
      gap-2
      min-w-20
      min-h-8
      max-w-full
"
  >
    <slot/>
  </button>
</template>